Сreate Сalculator
oleksandra-tseselska/new_start_pro_front_end pull request #3
Opened 2021-09-01 13:24 UTC by oleksandra-tseselska

2021-09-01 13:51 UTC, oleksandra-tseselska commented on js/homework_1.js
> +
Homework 3

2021-09-01 13:56 UTC, vladimirkr commented on js/homework_1.js
> +      someNum = someNum;
Смысла никакого в этом нет

2021-09-01 13:56 UTC, vladimirkr commented on js/homework_1.js
> +    if(addNum === Number(addNum)) {
Вспомните как проверять тип значения, я рассказывал несколько раз, посмотрите шпаргалку

2021-09-01 13:56 UTC, vladimirkr commented on js/homework_1.js
> +
перевод строки тут лишний

2021-09-01 13:56 UTC, vladimirkr commented on js/homework_1.js
> +
перевод строки тут лишний

2021-09-01 13:56 UTC, vladimirkr commented on js/homework_1.js
> +    } else {
else после ретерн бессмысленно

2021-09-01 13:56 UTC, vladimirkr commented on js/homework_1.js
> +    sub: (takeAwayNum) => someNum = someNum - takeAwayNum,
тоже нужна валидация

2021-09-01 13:56 UTC, vladimirkr commented on js/homework_1.js
> +    set: (newNum) => someNum = newNum,
тоже нужна валидация

2021-09-02 11:28 UTC, vladimirkr requested changes

2021-09-02 11:28 UTC, vladimirkr commented on js/homework_1.js
> +
лишний перевод строки

2021-09-02 11:28 UTC, vladimirkr commented on js/homework_1.js
> +    set: (newNum) => typeof newNum !== 'number' ? NaN :   someNum = newNum,
Сделай универсальную функцию валидатор чтоб переиспользовать код

2021-09-03 13:43 UTC, vladimirkr requested changes

2021-09-03 13:43 UTC, vladimirkr commented on js/homework_1.js
> +  function validator(validNum) {
переименуй в isNumber

2021-09-03 13:43 UTC, vladimirkr commented on js/homework_1.js
> +  if (validator(someNum) === true) {
if (isNumber(someNum))

2021-09-03 13:43 UTC, vladimirkr commented on js/homework_1.js
> +    };
```javascript
return typeof validNum === 'number'
```

2021-09-03 13:43 UTC, vladimirkr commented on js/homework_1.js
> +    set: (newNum) => validator(newNum) ? NaN :   someNum = newNum,
здесь и выше исправь
isNumber(newNum) ? someNum = newNum : NaN

2021-09-09 13:23 UTC, vladimirkr approved these changes

2021-09-09 15:23 UTC, merged